### ISSUE TITLE
Cut/Paste more than 3-4 documents at the same time cashes

### ISSUE THREAD

**Issue by eddymarques** [claroline/Claroline#651] opened 2015-02-04 08:20 UTC
It works for the first 2 documents but crashes for the rest

**Comment by ngodfraind** [comment] 2015-02-04 09:01
This could be caused because the copy is not or badly implemented for one of the documents (for instance, the wiki copy doesn't work anymore - I didn't correct it yet - but it may be true for other resource type).

**Comment by eddymarques** [comment] 2015-02-04 16:19
I tried with JPG image files, and TXT files.
Globaly with media files

**Comment by ngodfraind** [comment] 2015-02-04 16:21
Do you have an error log ? I can reproduce it.

2015-02-04 17:19 GMT+01:00 eddymarques <notifications@github.com>:

> I tried with JPG image files, and TXT files.
> Globaly with media files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/651#issuecomment-72884819>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by eddymarques** [comment] 2015-02-05 08:14
![image](https://cloud.githubusercontent.com/assets/3414956/6056871/4cdad774-ad17-11e4-8eaf-a6707ef0246b.png)

**Comment by ngodfraind** [comment] 2015-02-05 10:07
Thanks

2015-02-05 9:14 GMT+01:00 eddymarques <notifications@github.com>:

> [image: image]
> <https://cloud.githubusercontent.com/assets/3414956/6056871/4cdad774-ad17-11e4-8eaf-a6707ef0246b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/651#issuecomment-73009466>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by taniamcnamara** [comment] 2015-04-02 14:40
Any news on this problem? Is it fixable?
Thanks,
Tania

**Comment by ngodfraind** [comment] 2015-04-02 14:54
It should be fixed on the last version.

2015-04-02 16:40 GMT+02:00 taniamcnamara <notifications@github.com>:

> Any news on this problem? Is it fixable?
> Thanks,
> Tania
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/651#issuecomment-88931574>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Closed** 2016-03-23 12:26 UTC
Labels: Bug
